SENSOR:
  resolution:
    x: &SENSOR_X 96
    y: &SENSOR_Y 64
    chip_name: &CHIP_NAME "chip_mangut"

MODEL:
  operation_timeout: 30
  img:
    w: *SENSOR_X
    h: *SENSOR_Y
    # Should be R0, R90, R180, R270
    rotate: "R0"
    # Could be None, MX or MY
    flip: None
  chip_name: *CHIP_NAME
  modes: &MODES [
    # Label                 # Code
    ["Free running",         "0x00"  ],
    ["Time to First Spike",  "0x01"  ],
    ["Raw data",             "0x04"  ]
  ]
  device_registers: [
    # Label                 Address Value
    ["PIX_ON ON TIME",      "0x00", "0x00"],
    ["PIX_ON PERIOD",       "0x01", "0x00"],
    ["PIX_ON DELAY",        "0x02", "0x00"],
    ["RST_PIX ON TIME",     "0x03", "0x00"],
    ["RST_PERIPH ON TIME",  "0x04", "0x00"],
    ["TFS CLK PERIOD",      "0x05", "0x00"],
    ["N. of SAMPLES",       "0x06", "0x00"],
    ["SRAM DIV DIN",        "0x07", "0x00"],
    ["SPI_TX_BYTES",        "0x08", "0x00"],
    ["QI ON  TIME",         "0x09", "0x00"],
    ["QI OFF TIME",         "0x0A", "0x00"],
    ["N. of PULSES (TEST)", "0x0B", "0x00"],
    ["FREQ. DIV. (TEST)",   "0x0C", "0x00"],
    ["LASER PULSE WIDTH",   "0x0D", "0x00"],
    ["PDVS SAMPLES",        "0x0E", "0x00"],
    ["PDVS NTH",            "0x0F", "0x00"],
    ["CFG_LASER",            "0x10", "0x00"]
  ]
  dacs: &DACS [
    # Label              Address Channel  Value
    ["pullup_req_y",     "0x00", "0x00", "0x00"],
    ["pullup_req_x",     "0x00", "0x01", "0x00"],
    ["Vbias_comp",       "0x00", "0x02", "0x00"],
    ["Vcomp",            "0x00", "0x03", "0x00"],
    ["pulldown_bus_req", "0x01", "0x00", "0x00"],
    ["Vbias_pmos",       "0x01", "0x01", "0x00"],
    ["Vbias_nmos",       "0x01", "0x02", "0x00"]
  ]
  adcs: &ADCS [
    # ID      Channel     offset   slope           Label
    ["0x00",   "0x00",    "0",    "0.00080566",   "None"   ]
  ]
  adc_tmeas: 0.1 # 0.1 s
  chip_registers:
      REG_0:
        label: "REG PERIPH CFG"
        address: "0x01"
        signals: [
         # Bit   # Nbits   # Label
          ["4",   "1",      breq_nand_en         ],
          ["3",   "1",      latch_req_en         ],
          ["2",   "1",      latch_rst_en         ],
          ["1",   "1",      en_online_ram_data   ],
          ["0",   "1",      pu_boost_en          ]
        ]
  tools: [
    # Name            # Enable  # Update chip   # Update device
    ['Mux Selector',  False,     True,           False          ],
    ['PCB Switches',  True,     False,          False           ]
  ]

VIEW:
  main_panel_size:
    w: 1024
    h: 768
  image_panel_size:
    w: *SENSOR_X
    h: *SENSOR_Y
  control_panel:
    modes: *MODES
